FROM honeycomb/server

# The DEV, TEST, and PROD CONTAINERS are differentiated by the ENVIRONMENT VARIABLES
#   that are defined according to the respective CONTAINER. These environment variables
#   are called throughout configuration files in the APP_DIRECTORY (such as mix.ex).
#   also, these three CONTAINERS are differentiated by the tools available.

# The DEV container contains a development environment for HONEYCOMB.

RUN apt install -y emacs